name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

  push:
    branches:
      - main
    tags:
      - v*

env:
  IMAGE_NAME: goose-docker

jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Private Docker Registry
        uses: docker/login-action@v3
        with:
          registry: git.uncleched.com
          username: ${{ secrets.PRIVATEHUB_USERNAME }}
          password: ${{ secrets.PRIVATEHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            chekist32/${{ env.IMAGE_NAME }}
            git.uncleched.com/chekist32/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enabled=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag,pattern=v*

      - name: Build And Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}